### ISSUE TITLE
Cannot open admin interface

### ISSUE THREAD

**Issue by blablubbabcDEV** [Shopkeepers/Shopkeepers#394]
**Migrated from:** https://dev.bukkit.org/projects/shopkeepers/issues/393

**Originally posted by TechieV2 (Apr 21, 2016):** 

What steps will reproduce the problem?
1.Download plugin,
2.Start server
3.Issue command /shopkeeper
4. Sneek and right click on shopkeeperWhat is the expected output? What do you see instead?
Expeced to see interface to setup trades
I see normal trade interfaceWhat version of the product are you using?
LatestDo you have an error log of what happened?
Console showsÂ  "PlayerInteractEntityEvent" error - log here - http://pastebin.com/ay9Hhv1KPlease provide any additional information below.Thanks or looking in to this

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 21, 2016):** 

You have to update your spigot server to a later version.

**Comment by blablubbabcDEV** [comment]
**Originally commented by TechieV2 (Apr 21, 2016):** 

I have tried in 1.9 and 1.9.2 with the same results

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 21, 2016):** 

[at]TechieV2:
Well, you need a newer version of spigot for 1.9.x.
The error 'java.lang.NoSuchMethodError' says that Shopkeepers is trying to use a function of spigot which was added to spigot somewhere in newer versions, and which it cannot find in your version of spigot.

**Comment by blablubbabcDEV** [comment]
**Originally commented by TechieV2 (Apr 21, 2016):** 

Ok i e just done some testing and it worked on a testing 1.9.2 server, which im sure it didnt before. Is there anyway to get it working on just 1.9 and the file says it wirks on 1.8 & 1.9?

Thanks

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 21, 2016):** 

[at]TechieV2:
It works on the latest versions of 1.7, 1.8, and 1.9. There however is no separate support for the individual versions in-between..

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Apr 21, 2016)**
