### ISSUE TITLE
Can't edit the shopkeeper

### ISSUE THREAD

**Issue by Satino1** [Shopkeepers/Shopkeepers#594]
## Preliminaries:

* **Shopkeepers version:** `1.4.4`
* **Spigot version:** `1.14.3`
---

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`1.14.3`**) with the latest version of Shopkeepers (currently **`1.4.4`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

When I spawn a village, crouch and click on him, I cannot modify his name, set a price, change color or even delete him.
I put a selling villager, with a chest behind him, I'm not in creative. I did what was wrote, right clicked on the chest, I tried with quartz and cookies. 
When I crouch and right click I cannot edit a thing.

Here's the logs : 

> [15:38:27] [Server thread/ERROR]: Could not pass event InventoryClickEvent to Shopkeepers v2.6.0
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2162) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
> Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
> 	at com.nisovin.shopkeepers.ui.defaults.EditorHandler.isWindow(EditorHandler.java:667) ~[?:?]
> 	at com.nisovin.shopkeepers.ui.UIListener.validateSession(UIListener.java:40) ~[?:?]
> 	at com.nisovin.shopkeepers.ui.UIListener.onInventoryClick(UIListener.java:82) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-5f88938]
> 	... 17 more

**Comment by blablubbabc** [comment]
> Shopkeepers version: 1.4.4

I think you meant v2.6.0 (that's what your log says).
Anyways, you will have to update Shopkeepers to v2.7.2 in order to work with Spigot 1.4.x: https://dev.bukkit.org/projects/shopkeepers/files/2734200
